name: test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: npm i typescript -g
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - run: go get -t -v ./...
      - run: go test -race -coverprofile=coverage.out -covermode=atomic -timeout 600s
      - uses: codecov/codecov-action@v3
        with:
          version: 'v0.1.15'
